### PR TITLE
bug/#60 cannot login in live site

### LINKED ISSUE #60: Cannot login in Live Site
**Describe the bug**
When I try to login with my user in the System:
https://scmy-studyconnect-staging.pm4.init-lab.ch

I get redirected to localhost:3000

**To Reproduce**
1. Go to [StudyConnect Staging](https://scmy-studyconnect-staging.pm4.init-lab.ch)
2. Click on 'Sign in with microsoft'
3. Enter Login credentials for Test User

**Expected behavior**
Redirection should happen to https://scmy-studyconnect-staging.pm4.init-lab.ch/

**Additional Context**
Possible default next.js value is used because REDIRECT_URI is not set in the request sent to Microsoft.

**Screenshots**
Image
Image

### PR DESCRIPTION
**Pull request by Danbuch**
## Description

- Fixes the proper User Data submission from Microsoft to the backend.

## Checklist

Please make sure that the following items have been completed before submitting this pull request:

- [x] All issue acceptance criteria are fulfilled
- [x] All code has been properly tested
- [x] All tests pass successfully
- [x] Meets coding standards
- [x] Code has been properly documented with comments
- [x] Manual Testing was done by Developer and Reviewer
- [x] Refactoring is done (if needed)
- [x] Documentation (README/API/UX/ARC42) updated
- [x] Related non-linked issue is updated

### CODE REVIEW

**Review by AbdulBhatti2001 — COMMENTED** [review]
image
Bei mir kommt immer noch diese Meldung.
Ich weiss nicht wo das Problem liegen könnte, hab schon fast alles probiert...

**Comment by Danbuch** [comment]
> image I keep getting this message. I don’t know where the problem could be, I’ve already tried almost everything...

In case someone else has this problem.
Please use the updated .env file form our Teams channel to make sure you have the correct links and API connections.

**Review by AbdulBhatti2001 — DISMISSED** [review]

File: src/app/auth/redirect/route.ts [hunk 1]
```diff
@@ -4,10 +4,11 @@ import { jwtDecode } from 'jwt-decode';
 
 interface MicrosoftToken {
   oid: string;
-  email?: string;
-  name?: string;
```
Comment (adr1anmart1nez) [inline src/app/auth/redirect/route.ts:8]: The code shows errors because `name` is missing from `MicrosoftToken`. 

image

To fix this, simply insert the `name` back or remove all the code that uses `name`. 
```JavaScript
  name?: string;
```

**Review by adr1anmart1nez — CHANGES_REQUESTED** [review]

**Comment by adr1anmart1nez** [comment]
Furthermore, there is an issue where the main page doesn't load because of these lines in Sumaya's previous PR:

image

Atm, the API doesn't return any `name` field in the json, meaning the home page will always be blank.

```
{"firstName":"Adrian","lastName":"Martinez","email":"adrian.martinez@studyconnectaoutlook.onmicrosoft.com"}
```

Screen Shot 2025-04-22 at 16 56 14

**Comment by Danbuch** [comment]
@adr1anmart1nez applied changes to make use of the user name in the decoded token.
I realize that the token that was deserialized in the login/redirect/route.ts didn't contain any given_name or family_name.
This might be interesting to look at, because the token in api/me/route.ts contains the given_name and family_name values.

**Review by adr1anmart1nez — APPROVED** [review]
This needs to be handled better, otherwise the user will keep seeing a blank page as long as there is an issue with fetching user information which is an unwanted behavior. But imo this is low priority and can be refactored in the future.

`src/app/auth/redirect/route.ts`:
```
    if (!userName) return null;
```

**Comment by Danbuch** [comment]
> This needs to be handled better, otherwise the user will keep seeing a blank page as long as there is an issue with fetching user information which is an unwanted behavior. But imo this is rather low priority and can be refactored in the future.
> 
> `src/app/auth/redirect/route.ts`:
> 
> ```
>     if (!userName) return null;
> ```

@adr1anmart1nez added an issue for this. See (#62)

**Review by AlexSivapalan — APPROVED** [review]
